- name: Install unzip on Debian-based systems
  ...
  
- name: Install unzip on RedHat-based systems
  ...
  
- name: Install Java 17 on Debian-based systems
  ...
  
- name: Install Java 17 on RedHat-based systems
  ...
  
- name: download Hazelcast
  get_url: 
    url: https://repository.hazelcast.com/download/hazelcast-enterprise/hazelcast-enterprise-{{ hazelcast_version }}.zip 
    dest: /root/hazelcast-enterprise-{{ hazelcast_version }}.zip
  
- name: unarchive Hazelcast
  unarchive: 
    src: /root/hazelcast-enterprise-{{ hazelcast_version }}.zip 
    remote_src: True 
    dest: /opt
  
- name: create /opt/hazelcast
  shell: cp -r /opt/hazelcast-enterprise-{{ hazelcast_version }} /opt/hazelcast creates=/opt/hazelcast
  
- name: Create  /opt/hazelcast/logs if it does not exist
  ...
  
- name: print groups[hazelcast_group_name]
  ...

- name: print hostvars[host]
  ...

- name: put Hazelcast config file
  ...

- name: put systemd unit file
  ...

- name: configure hazelcast service but do not start
  ...
