- name: download Hazelcast
  get_url: url=https://repository.hazelcast.com/download/hazelcast-enterprise/hazelcast-enterprise-5.3.1.zip

- name: unarchive Hazelcast
  unarchive: src=/root/hazelcast-enterprise-5.3.1.zip remote_src=True dest=/opt

- name: create /opt/hazelcast
  shell: cp -r /opt/hazelcast-enterprise-5.3.1 /opt/hazelcast creates=/opt/hazelcast

- name: print groups[hazelcast_group_name]
  debug: var=groups[hazelcast_group_name]

- name: print hostvars[host]
  debug: var=hostvars[groups[hazelcast_group_name][0]]

- name: put Hazelcast config file
  template: src=hazelcast.xml dest=/opt/hazelcast/config/hazelcast.xml backup=yes

- name: put systemd unit file
  template: src=hazelcast.service dest=/etc/systemd/system/hazelcast.service backup=yes
  notify: systemctl daemon-reload

- name: enable hazelcast service
  service: name=hazelcast state=started enabled=yes
